/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Mix&Mingle API
 * 
Mix&Mingle API Server

 * OpenAPI spec version: 0.6.0
 */
import {
  z as zod
} from 'zod'

/**
 * 사용자 목록을 조회합니다.
 * @summary 사용자 목록 조회
 */
export const apiUsersGetResponseItem = zod.object({
  "user_id": zod.string(),
  "name": zod.string(),
  "birth_date": zod.string().date(),
  "job": zod.string().optional(),
  "personality": zod.enum(['내향적', '양면성', '외향적']).or(zod.null()).optional(),
  "interest": zod.array(zod.string()).optional(),
  "created_at": zod.string(),
  "updated_at": zod.string()
})
export const apiUsersGetResponse = zod.array(apiUsersGetResponseItem)

/**
 * 사용자를 생성합니다.
 * @summary 사용자 생성
 */
export const apiUsersPostBody = zod.object({
  "user_id": zod.string(),
  "name": zod.string(),
  "birth_date": zod.string().date(),
  "job": zod.string().optional(),
  "personality": zod.enum(['내향적', '양면성', '외향적']).or(zod.null()).optional(),
  "interest": zod.array(zod.string()).optional()
})

/**
 * 사용자를 조회합니다.
 * @summary 사용자 조회
 */
export const apiUsersUserIdGetParams = zod.object({
  "user_id": zod.string()
})

export const apiUsersUserIdGetResponse = zod.object({
  "user_id": zod.string(),
  "name": zod.string(),
  "birth_date": zod.string().date(),
  "job": zod.string().optional(),
  "personality": zod.enum(['내향적', '양면성', '외향적']).or(zod.null()).optional(),
  "interest": zod.array(zod.string()).optional(),
  "created_at": zod.string(),
  "updated_at": zod.string()
})

/**
 * 사용자 정보를 수정합니다.
 * @summary 사용자 수정
 */
export const apiUsersUserIdPutParams = zod.object({
  "user_id": zod.string()
})

export const apiUsersUserIdPutBody = zod.object({
  "name": zod.string().or(zod.null()),
  "birth_date": zod.string().date().or(zod.null()),
  "job": zod.string().or(zod.null()).optional(),
  "personality": zod.enum(['내향적', '양면성', '외향적']).or(zod.null()).optional(),
  "interest": zod.array(zod.string()).or(zod.null()).optional()
})

export const apiUsersUserIdPutResponse = zod.object({
  "user_id": zod.string(),
  "name": zod.string(),
  "birth_date": zod.string().date(),
  "job": zod.string().optional(),
  "personality": zod.enum(['내향적', '양면성', '외향적']).or(zod.null()).optional(),
  "interest": zod.array(zod.string()).optional(),
  "created_at": zod.string(),
  "updated_at": zod.string()
})

/**
 * 사용자를 삭제합니다.
 * @summary 사용자 삭제
 */
export const apiUsersUserIdDeleteParams = zod.object({
  "user_id": zod.string()
})

