/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Mix&Mingle API
 * 
Mix&Mingle API Server

 * OpenAPI spec version: 0.6.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary 소켓 테스트
 */
export const apiStaticGetResponse = zod.any()

/**
 * @summary 이벤트 시작
 */
export const apiEventEventIdStartGetParams = zod.object({
  "event_id": zod.number()
})

export const apiEventEventIdStartGetResponse = zod.any()

/**
 * @summary 퀴즈 시작
 */
export const apiEventEventIdStartQuizGetParams = zod.object({
  "event_id": zod.number()
})

export const apiEventEventIdStartQuizGetResponse = zod.any()

/**
 * 네트워킹을 시작하는 메시지를 보냅니다.
 * @summary 네트워킹 시작
 */
export const apiEventEventIdStartNetworkingGetParams = zod.object({
  "event_id": zod.number()
})

export const apiEventEventIdStartNetworkingGetResponse = zod.any()

/**
 * 네트워킹 대화 주제를 생성하는 메시지를 보냅니다.
 * @summary 네트워킹 대화 주제 생성
 */
export const apiEventEventIdTopicGenerateGetParams = zod.object({
  "event_id": zod.number()
})

export const apiEventEventIdTopicGenerateGetResponse = zod.any()

